repos:

# Linting with ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev:  v0.14.6
  hooks:
    - id: ruff-check
      args: [ --select, I, --fix ]
    - id: ruff-format

# Type checking with mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy