name: End to end tests

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          tags: portalias:test
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: ${{ runner.temp }}/myimage.tar

  create-matrix:
    name: Create test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create test matrix
        id: set-matrix
        run: |
          json=$(find tests -type d -name 'test_*' | jq -Rsc '{test_directory: split("\n") | map(select(. != ""))}')
          echo "Matrix JSON: $json"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"

  run-end-to-end-test:
    name: Run end to end test
    needs:
      - create-matrix
      - build
    runs-on: ubuntu-latest
    # Avoid running this job if there are no test directories found
    if: join(fromJson(needs.create-matrix.outputs.matrix).test_directory, ',') != ''
    strategy:
      matrix: ${{fromJson(needs.create-matrix.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: myimage
          path: ${{ runner.temp }}
      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/myimage.tar
      - name: Run test
        run: |
          cd ${{ matrix.test_directory }}
          chmod +x test.sh
          ./test.sh
